# Stage 1: Build
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src


COPY BookApp.api.csproj ./
RUN dotnet restore


COPY . ./


RUN dotnet publish -c Release -o /app
RUN dotnet ef database update

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app


COPY --from=build /app .


EXPOSE 5267


ENTRYPOINT ["dotnet", "BookApp.api.dll"]